Add empty Android.mk
* Avoid build target conflict

  build/make/core/base_rules.mk:342:
  error: kernel/xiaomi/msm8996/KernelSU/userspace/su/jni:
  MODULE.TARGET.EXECUTABLES.su already defined by system/extras/su.

Signed-off-by: Marco Zanin <mrczn.bb@gmail.com>